"""Type stubs for the Rust native extension `touch_glove_rust._rust`."""

from typing import Iterator, List, Optional
import numpy as np

IMAGE_WIDTH: int
IMAGE_HEIGHT: int  
IMAGE_CHANNELS: int
IMAGE_BYTES: int

def list_ports() -> List[str]: ...

class Frame:
    channel: int
    sensor_id: str
    seq_id: int
    timestamp_us: int

    @property
    def disp(self) -> Optional[np.ndarray]: ...
    @property
    def force_field(self) -> Optional[np.ndarray]: ...
    def __repr__(self) -> str: ...

class FrameBatch:
    frames: List[Optional[Frame]]
    timestamp: float

    @property
    def total_frames(self) -> int: ...
    def __iter__(self) -> Iterator[Frame]: ...
    def __repr__(self) -> str: ...

class TouchGlove:
    def __init__(
        self,
        port: Optional[str] = None,
        auto_init: bool = True,
        force_model: Optional[str] = None,
        pos_model: Optional[str] = None,
        dense_model: Optional[str] = None,
        enable_inference: bool = True,
    ) -> None: ...

    # Context manager
    def __enter__(self) -> "TouchGlove": ...
    def __exit__(self, exc_type: object, exc_val: object, exc_tb: object) -> bool: ...

    def open(self, port: str) -> bool: ...
    def close(self) -> None: ...
    def reinit(self) -> bool: ...
    def sync_time(self) -> bool: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def poll(self) -> FrameBatch: ...
    def stream(
        self,
        max_frames: Optional[int] = None,
        timeout: Optional[float] = None,
    ) -> Iterator[FrameBatch]: ...
    def get_bytes_per_second(self) -> float: ...
    def get_total_bytes(self) -> int: ...
    def get_dense_update_count(self) -> int: ...

    @property
    def is_open(self) -> bool: ...
    @property
    def is_streaming(self) -> bool: ...
    @property
    def sensor_ids(self) -> List[str]: ...

    @staticmethod
    def list_ports() -> List[str]: ...
